---
- name: dci-downloader
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Import remoteci SSL keys
      vars:
        dci_import_keys_remoteci_id: '{{ remoteci_id }}'
      include_role:
        name: dci-import-keys

    - name: Retrieve components
      vars:
        dci_retrieve_component_local_repo: '{{ local_repo }}'
        dci_retrieve_component_component_id: '{{ item.id }}'
        dci_retrieve_component_component_name: '{% if item.type == "Compose" %}{{ topic_name }}{% else %}{{ item.type }}{% endif %}'
      include_role:
        name: dci-retrieve-component
      with_list: '{{ components }}'
